# Generated by Django 3.2.13 on 2022-05-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadscheet',
            fields=[
                ('number', models.IntegerField()),
                ('order', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('cost_dollars', models.IntegerField()),
                ('delivery_time', models.DateField()),
                ('cost_ru', models.FloatField(blank=True)),
            ],
        ),
    ]
