# Generated by Django 3.2.13 on 2022-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadscheet',
            name='is_active',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.AddField(
            model_name='spreadscheet',
            name='is_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spreadscheet',
            name='is_created',
            field=models.DateField(default='2022-05-22'),
        ),
    ]
