# Generated by Django 3.2.13 on 2022-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapi', '0002_auto_20220522_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadscheet',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
