# Generated by Django 3.2.13 on 2022-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapi', '0003_spreadscheet_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadscheet',
            name='is_overdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spreadscheet',
            name='is_send',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='spreadscheet',
            name='is_send_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spreadscheet',
            name='is_created',
            field=models.DateField(default='2022-05-23'),
        ),
    ]
