# Generated by Django 3.2.13 on 2022-05-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapi', '0004_auto_20220523_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadscheet',
            name='is_send',
            field=models.DateTimeField(blank=True),
        ),
    ]
