# Generated by Django 3.2.13 on 2022-05-23 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapi', '0006_alter_spreadscheet_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadscheet',
            name='is_send',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 19, 3, 30, 412246, tzinfo=utc)),
        ),
    ]
