# Generated by Django 3.2.13 on 2022-05-23 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapi', '0009_alter_spreadscheet_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadscheet',
            name='is_send',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 19, 6, 50, 185755)),
        ),
    ]
