# Generated by Django 3.2.13 on 2022-05-23 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapi', '0010_alter_spreadscheet_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadscheet',
            name='is_send',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 19, 7, 9, 829701, tzinfo=utc)),
        ),
    ]
