# Generated by Django 3.2.13 on 2022-05-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapi', '0012_remove_spreadscheet_is_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadscheet',
            name='is_created',
        ),
    ]
