version: '3.7'

services:
  db:
    image: postgres:14.2
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sheets
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data